feed_id: feed id
feed_title: feed title
author: author
publish_directory: site
#full path from remote ssh home to bare repo for deployment git tracking
repo_path: path to bare repo for remote tracking

#full path from remote ssh home to deployment repo !!-Different than bare-!!
work_path: path to working tree where site gets deployed

#ssh info for remote
host: remote ip address
port: remote port
username: remote username

deploy: false
