#!/usr/bin/env python3

import sys
import os
import pygit2

sys.path.append(os.getcwd())

from gitatom import __main__ as main
from gitatom import build


current_directory = os.getcwd()
repo_path = pygit2.discover_repository(current_directory)
repo = pygit2.Repository(repo_path)
staged_files = main.git_staged_files(repo)
files = main.on_commit(staged_files)
if os.path.exists('site/style.css'):
    files.append('site/style.css')
main.gitatom_git_add(repo, files)

