#!/usr/bin/env python3

import os
import sys
import pygit2

if "GITATOM_PATH" in os.environ:
    gitatom_path = os.environ["GITATOM_PATH"]
else:
    gitatom_path = ".."
sys.path.append(gitatom_path)

from gitatom import __main__ as main
from gitatom import build


repo_path = pygit2.discover_repository(".")
repo = pygit2.Repository(repo_path)
staged_files = main.git_staged_files(repo)
files = main.on_commit(staged_files)
if os.path.exists('site/style.css'):
    files.append('site/style.css')
main.gitatom_git_add(repo, files)

